parameters:
#    acme_todo_list.example.class: Acme\TodoListBundle\Example

services:
#    acme_todo_list.example:
#        class: %acme_todo_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
